#!/bin/sh

# Where am I?
SCRIPT=$(readlink -f "$0")
REPO_DIR=$(dirname "$SCRIPT")

HOSTS_FILE="$REPO_DIR/ansible/hosts"

ansible-playbook -i "$HOSTS_FILE" "$REPO_DIR/ansible/playbook.yml" -K --extra-vars "repo_dir=$REPO_DIR"
